/**
 * Generated by tsnapi — public API snapshot of `leylines/browser`
 */
// #region Interfaces
export interface BrowserLogger {
  debug(_: string, _: string, _?: JsonObject): void;
  info(_: string, _: string, _?: JsonObject): void;
  warn(_: string, _: string, _?: JsonObject): void;
  error(_: string, _: string, _?: JsonObject, _?: unknown): void;
  write(_: LogLevel, _: string, _: string, _?: JsonObject, _?: unknown): void;
}
export interface BrowserLoggerConnectOptions extends BrowserLoggerOptions {
  captureConsole?: boolean | LogLevel[];
  captureErrors?: boolean;
  captureRejections?: boolean;
}
export interface BrowserLoggerOptions {
  endpoint: string;
  scope?: string;
  metadata?: JsonObject;
  properties?: JsonObject;
  fetch?: typeof fetch;
  test?: boolean;
}
export interface BrowserLoggerSingleton extends BrowserLogger {
  connect(_: BrowserLoggerConnectOptions): BrowserLoggerSingleton;
}
// #endregion

// #region Variables
export declare const logger: BrowserLoggerSingleton;
// #endregion
