/**
 * Generated by tsnapi — public API snapshot of `leylines`
 */
// #region Interfaces
export interface CollapsedValue {
  id: string;
  entryId: string;
  path: string;
  value: JsonValue;
}
export interface ErrorDetails {
  name?: string;
  message: string;
  stack?: string;
  cause?: JsonValue;
}
export interface LogEntry {
  id: string;
  sequence: number;
  timestamp: string;
  level: LogLevel;
  scope: string;
  message: string;
  metadata: JsonObject;
  properties: JsonObject;
  error?: ErrorDetails;
}
export interface LogEntryInput {
  id?: string;
  timestamp?: Date | string;
  level: LogLevel;
  scope: string;
  message: string;
  metadata?: JsonObject;
  properties?: JsonObject;
  error?: unknown;
}
export interface LoggerOptions {
  scope: string;
  properties?: JsonObject;
  metadata?: JsonObject;
}
export interface LoggerWriteOptions {
  properties?: JsonObject;
  metadata?: JsonObject;
  error?: unknown;
  timestamp?: Date | string;
}
export interface LogPage {
  entries: LogEntry[];
  nextBefore?: string;
  nextAfter?: string;
}
export interface LogQuery {
  since?: Date | string;
  until?: Date | string;
  before?: string;
  after?: string;
  levels?: LogLevel[];
  minLevel?: LogLevel;
  scope?: string;
  scopePrefix?: string;
  text?: string;
  regex?: string | RegExp;
  properties?: PropertyFilter[];
  includeDebug?: boolean;
  limit?: number;
}
export interface OpenScopedLogsOptions {
  path?: string;
  production?: boolean;
  test?: boolean;
  retention?: RetentionOptions;
  redaction?: RedactionOptions;
  collapseAboveBytes?: number;
}
export interface PropertyFilter {
  path: string;
  equals: JsonValue;
}
export interface RedactionOptions {
  rules?: RedactionRule[];
}
export interface RedactionRule {
  name?: string | RegExp;
  value?: string | RegExp;
  replacement?: string;
}
export interface RetentionOptions {
  maxEntries?: number;
  maxAgeMs?: number;
}
export interface ScopedLogs {
  readonly enabled: boolean;
  readonly store: LogStore | undefined;
  logger(_: LoggerOptions | string): ScopedLogger;
  query(_?: LogQuery): ReturnType<LogStore['query']>;
  tail(_?: LogQuery, _?: {
    signal?: AbortSignal;
  }): AsyncIterable<LogEntry>;
  expand(_: string): ReturnType<LogStore['expand']>;
  listScopes(): string[];
  close(): void;
}
// #endregion

// #region Types
export type JsonObject = {
  [key: string]: JsonValue;
};
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | {
  [key: string]: JsonValue;
};
export type LogLevel = 'debug' | 'info' | 'warn' | 'error';
// #endregion

// #region Classes
export declare class LogStore {
  #private;
  readonly path: string;
  constructor(_: OpenLogStoreOptions);
  write(_: LogEntryInput): LogEntry;
  query(_?: LogQuery): LogPage;
  listScopes(): string[];
  expand(_: string): CollapsedValue | undefined;
  tail(_?: LogQuery, _?: {
    signal?: AbortSignal;
  }): AsyncIterable<LogEntry>;
  close(): void;
}
export declare class ScopedLogger {
  #private;
  readonly scope: string;
  constructor(_: LogStore | undefined, _: LoggerOptions);
  child(_?: Partial<LoggerOptions> & {
    scope?: string;
  }): ScopedLogger;
  debug(_: string, _?: LoggerWriteOptions): LogEntry | undefined;
  info(_: string, _?: LoggerWriteOptions): LogEntry | undefined;
  warn(_: string, _?: LoggerWriteOptions): LogEntry | undefined;
  error(_: string, _?: LoggerWriteOptions): LogEntry | undefined;
  write(_: LogLevel, _: string, _?: LoggerWriteOptions): LogEntry | undefined;
}
// #endregion

// #region Functions
export declare function defaultStorePath(): string;
export declare function openLogStore(_: OpenLogStoreOptions): LogStore;
export declare function openScopedLogs(_?: OpenScopedLogsOptions): ScopedLogs;
// #endregion
