/**
 * Generated by tsnapi — public API snapshot of `leylines/tauri`
 */
// #region Interfaces
export interface TauriLoggerOptions {
  logger?: BrowserLogger;
  test?: boolean;
  scope?: string;
  metadata?: JsonObject;
  properties?: JsonObject;
}
// #endregion

// #region Types
export type DetachTauriLogger = () => void;
// #endregion

// #region Functions
export declare function attachTauriLogger(_?: TauriLoggerOptions): DetachTauriLogger;
// #endregion
