/**
 * Generated by tsnapi — public API snapshot of `leylines/vite`
 */
// #region Interfaces
export interface LeylinesVitePluginOptions extends OpenScopedLogsOptions {
  endpoint?: string;
  scope?: string;
  captureConsole?: boolean | LogLevel[];
  captureErrors?: boolean;
  captureRejections?: boolean;
  production?: boolean;
  stripProduction?: boolean;
  metadata?: JsonObject;
  posthog?: boolean | PostHogViteOptions;
  viteLogger?: boolean | ViteLoggerCaptureOptions;
  captureViteLogger?: boolean | ViteLoggerCaptureLevel[];
}
export interface PostHogViteOptions {
  endpoint?: string;
  scope?: string;
}
export interface ViteLoggerCaptureOptions {
  scope?: string;
  levels?: ViteLoggerCaptureLevel[];
}
export interface VitePluginLike {
  name: string;
  apply?: 'serve' | 'build';
  configResolved(_: ViteResolvedConfigLike): void;
  configureServer(_: ViteServerLike): void;
  transformIndexHtml(_: string): string;
  transform(_: string, _?: string): string | null;
  closeBundle(): void;
}
// #endregion

// #region Types
export type ViteLoggerCaptureLevel = Extract<LogLevel, 'info' | 'warn' | 'error'>;
// #endregion

// #region Functions
export declare function leylines(_?: LeylinesVitePluginOptions): VitePluginLike;
// #endregion