/**
 * Generated by tsnapi — public API snapshot of `leylines/vite`
 */
// #region Interfaces
export interface ScopedLogsVitePluginOptions extends OpenScopedLogsOptions {
  endpoint?: string;
  scope?: string;
  captureConsole?: boolean | LogLevel[];
  captureErrors?: boolean;
  captureRejections?: boolean;
  production?: boolean;
  metadata?: JsonObject;
}
export interface VitePluginLike {
  name: string;
  apply?: 'serve' | 'build';
  configResolved(_: {
    mode?: string;
    command?: string;
  }): void;
  configureServer(_: ViteServerLike): void;
  transformIndexHtml(_: string): string;
  closeBundle(): void;
}
// #endregion

// #region Functions
export declare function scopedLogsVitePlugin(_?: ScopedLogsVitePluginOptions): VitePluginLike;
// #endregion